services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: "http://main%5Cdlupdate:3sd4y-K8yf3@proxy.gsu.by:800/"
        HTTPS_PROXY: "http://main%5Cdlupdate:3sd4y-K8yf3@proxy.gsu.by:800/"
        NO_PROXY: "localhost,127.0.0.1,db,nginx,.local"
    container_name: dl_ai_web
    command: daphne -b 0.0.0.0 -p 8000 DjangoTest.asgi:application
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HTTP_PROXY=http://main%5Cdlupdate:3sd4y-K8yf3@proxy.gsu.by:800/
      - HTTPS_PROXY=http://main%5Cdlupdate:3sd4y-K8yf3@proxy.gsu.by:800/
      - NO_PROXY=localhost,127.0.0.1,db,nginx,.local
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: postgres:14
    container_name: dl_ai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dlaibd
      POSTGRES_PASSWORD: dlaibd
      POSTGRES_DB: dl_ai
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: dl_ai_nginx
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - web
    networks:
      - shared-network

volumes:
  postgres_data:
    external: true
    name: dlai_postgres_data
  static_volume:


networks:
  shared-network:
    external: true
