# Generated by Django 5.1.4 on 2026-04-04 00:00

from django.db import migrations, models


def create_default_ai_app_settings(apps, schema_editor):
    AIAppSettings = apps.get_model('ai', 'AIAppSettings')
    AIAppSettings.objects.get_or_create(id=1, defaults={"is_enabled": True})


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI app setting',
                'verbose_name_plural': 'AI app settings',
            },
        ),
        migrations.RunPython(create_default_ai_app_settings, migrations.RunPython.noop),
    ]
