# Generated by Django 5.1.4 on 2026-04-16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiappsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(db_index=True, max_length=128)),
                ('model_title', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('window_date', models.DateField(db_index=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'AI model availability',
                'verbose_name_plural': 'AI model availability',
                'ordering': ('model_title',),
            },
        ),
        migrations.CreateModel(
            name='AIModelHealthRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'AI model health run',
                'verbose_name_plural': 'AI model health runs',
                'ordering': ('-window_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='aimodelavailability',
            constraint=models.UniqueConstraint(fields=('model_key', 'window_date'), name='ai_model_availability_key_window_uniq'),
        ),
    ]
