# Generated by Django 5.1.4 on 2026-05-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aimodelavailability_aimodelhealthrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editable_prompts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
