# Generated by Django 5.1.4 on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_prompt_owner_from_editors(apps, schema_editor):
    Prompt = apps.get_model("ai", "Prompt")

    for prompt in Prompt.objects.all().iterator():
        editor_ids = list(
            prompt.editors.order_by("id").values_list("id", flat=True)[:1]
        )
        if editor_ids:
            prompt.owner_id = editor_ids[0]
            prompt.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_prompt_editors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_prompts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            backfill_prompt_owner_from_editors,
            migrations.RunPython.noop,
        ),
    ]
