# Generated by Django 5.1.4 on 2026-05-09

from django.db import migrations


def merge_tester_group_into_prompt_developer(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    prompt_developer_group, _ = Group.objects.get_or_create(name="prompt_developer")
    tester_group = Group.objects.filter(name="tester").first()
    if not tester_group:
        return

    prompt_developer_group.permissions.add(*tester_group.permissions.all())
    for user in tester_group.user_set.all():
        user.groups.add(prompt_developer_group)

    tester_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_prompt_owner"),
    ]

    operations = [
        migrations.RunPython(
            merge_tester_group_into_prompt_developer,
            migrations.RunPython.noop,
        ),
    ]
