# Generated by Django 5.1.4 on 2026-05-16

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_merge_tester_into_prompt_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(db_index=True, help_text='User ID from dl.gsu.by API', max_length=255, unique=True)),
                ('external_login', models.CharField(help_text='Last known login/nickname from dl.gsu.by', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_dl_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External DL Account',
                'verbose_name_plural': 'External DL Accounts',
            },
        ),
    ]
