# Generated by Django 5.1.4 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_external_dl_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldlaccount",
            name="external_first_name",
            field=models.CharField(blank=True, default="", help_text="First name from dl.gsu.by", max_length=255),
        ),
        migrations.AddField(
            model_name="externaldlaccount",
            name="external_last_name",
            field=models.CharField(blank=True, default="", help_text="Last name from dl.gsu.by", max_length=255),
        ),
    ]
