# Generated by Django 5.1.4 on 2026-05-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_external_dl_account_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.topic'),
        ),
    ]
