# Generated by Django 5.1.4 on 2026-06-14 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_alter_prompt_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_override',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='prompt',
            table='ai_prompt',
        ),
        migrations.CreateModel(
            name='SharedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(max_length=255)),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editors', models.ManyToManyField(blank=True, related_name='editable_shared_prompts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_prompts', to=settings.AUTH_USER_MODEL)),
                ('programming_languages', models.ManyToManyField(blank=True, related_name='shared_prompts', to='ai.programminglanguage')),
            ],
            options={
                'verbose_name': 'Общий препромпт',
                'verbose_name_plural': 'Общие препромпты',
                'db_table': 'ai_sharedprompt',
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='shared_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_prompts', to='ai.sharedprompt'),
        ),
    ]
