# Generated by Django 5.1.4 on 2026-06-14 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_to_ru(apps, schema_editor):
    """Copy current base names/texts into Russian localized fields."""
    Topic = apps.get_model('ai', 'Topic')
    Prompt = apps.get_model('ai', 'Prompt')
    SharedPrompt = apps.get_model('ai', 'SharedPrompt')

    for topic in Topic.objects.all():
        if topic.topic_name and not topic.topic_name_ru:
            topic.topic_name_ru = topic.topic_name
            topic.save(update_fields=['topic_name_ru'])

    for prompt in Prompt.objects.all():
        fields = []
        if prompt.prompt_name and not prompt.prompt_name_ru:
            prompt.prompt_name_ru = prompt.prompt_name
            fields.append('prompt_name_ru')
        if prompt.prompt_text and not prompt.prompt_text_ru:
            prompt.prompt_text_ru = prompt.prompt_text
            fields.append('prompt_text_ru')
        if fields:
            prompt.save(update_fields=fields)

    for shared in SharedPrompt.objects.all():
        fields = []
        if shared.prompt_name and not shared.prompt_name_ru:
            shared.prompt_name_ru = shared.prompt_name
            fields.append('prompt_name_ru')
        if shared.prompt_text and not shared.prompt_text_ru:
            shared.prompt_text_ru = shared.prompt_text
            fields.append('prompt_text_ru')
        if fields:
            shared.save(update_fields=fields)


def reverse_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_migrate_pascal_to_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt_name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_name_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_name_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_text_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sharedprompt',
            name='prompt_text_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(copy_existing_to_ru, reverse_copy),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('user_full_name', models.CharField(blank=True, max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('websocket', 'WebSocket'), ('arm', 'ARM')], default='websocket', max_length=32)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('model_names', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI request log',
                'verbose_name_plural': 'AI request logs',
                'db_table': 'ai_airequestlog',
                'ordering': ('-sent_at',),
            },
        ),
    ]
