# Generated by Django 5.1.4 on 2026-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_prompt_prompt_name_en_prompt_prompt_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='programming_language_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='programming_language_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
