# Generated by Django 5.1.4 on 2026-06-14

from django.db import migrations


def ensure_all_users_prompt_developer(apps, schema_editor):
    """Add every existing user to the prompt_developer group."""
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    group, _ = Group.objects.get_or_create(name="prompt_developer")
    for user in User.objects.iterator():
        user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0013_airequestlog_context_fields"),
    ]

    operations = [
        migrations.RunPython(
            ensure_all_users_prompt_developer,
            migrations.RunPython.noop,
        ),
    ]
