# Generated by Django 5.1.4 on 2026-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_ensure_all_users_prompt_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='mode',
            field=models.CharField(blank=True, choices=[('chat', 'Чат'), ('solve', 'Решить задачу'), ('find_error', 'Найти ошибку'), ('arm', 'ARM')], default='', max_length=16),
        ),
    ]
