# Generated by Django 5.1.4 on 2026-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_airequestlog_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelavailability',
            name='last_http_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
