# Generated by Django 5.1.4 on 2026-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_aimodelavailability_last_http_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text',
            field=models.TextField(help_text='Доступные плейсхолдеры: {language}/{язык} - язык программирования, {topic}/{тема} - тема.'),
        ),
    ]
