# Generated by Django 5.1.4 on 2026-06-16 12:50

from django.db import migrations, models


DEFAULT_PROMPTS = {
    "solve": {
        "prompt_name": "Default: Solve task",
        "prompt_text": "У меня есть задача по программированию на языке {language}, тема {topic}. Реши задачу.\n\nЗадача:\n{message}",
        "prompt_text_ru": "У меня есть задача по программированию на языке {language}, тема {topic}. Реши задачу.\n\nЗадача:\n{message}",
        "prompt_text_en": "I have a programming problem in {language}, topic {topic}. Solve it.\n\nProblem:\n{message}",
        "prompt_text_fr": "J'ai un problème de programmation en {language}, sujet {topic}. Résolvez-le.\n\nProblème:\n{message}",
    },
    "find_error": {
        "prompt_name": "Default: Find error",
        "prompt_text": "У меня есть задача по программированию на языке {language}, тема {topic}. Я написал код, но он не работает. Найди ошибку.\n\nЗадача:\n{message}\n\nКод:\n{code}",
        "prompt_text_ru": "У меня есть задача по программированию на языке {language}, тема {topic}. Я написал код, но он не работает. Найди ошибку.\n\nЗадача:\n{message}\n\nКод:\n{code}",
        "prompt_text_en": "I have a programming problem in {language}, topic {topic}. I wrote code, but it does not work. Find the error.\n\nProblem:\n{message}\n\nCode:\n{code}",
        "prompt_text_fr": "J'ai un problème de programmation en {language}, sujet {topic}. J'ai écrit du code, mais il ne fonctionne pas. Trouvez l'erreur.\n\nProblème:\n{message}\n\nCode:\n{code}",
    },
}


def create_default_shared_prompts(apps, schema_editor):
    SharedPrompt = apps.get_model("ai", "SharedPrompt")
    for mode, fields in DEFAULT_PROMPTS.items():
        SharedPrompt.objects.get_or_create(mode=mode, defaults=fields)


def remove_default_shared_prompts(apps, schema_editor):
    SharedPrompt = apps.get_model("ai", "SharedPrompt")
    SharedPrompt.objects.filter(mode__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_alter_sharedprompt_prompt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedprompt',
            name='mode',
            field=models.CharField(blank=True, choices=[('', '—'), ('chat', 'Chat'), ('solve', 'Solve'), ('find_error', 'Find error')], help_text='Если указан, препромпт используется как системный шаблон для соответствующего режима.', max_length=16, null=True, verbose_name='Системный режим'),
        ),
        migrations.AddConstraint(
            model_name='sharedprompt',
            constraint=models.UniqueConstraint(condition=models.Q(mode__isnull=False) & ~models.Q(mode=''), fields=('mode',), name='unique_sharedprompt_mode_when_set'),
        ),
        migrations.RunPython(create_default_shared_prompts, remove_default_shared_prompts),
    ]
