# Generated by Django 5.1.4 on 2026-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0018_sharedprompt_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelTokenBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Provider/account name, e.g. «SambaNova» or «DeepSeek».', max_length=128, unique=True)),
                ('total_limit', models.PositiveBigIntegerField(help_text='Total token allowance.')),
                ('issued_at', models.DateField(help_text='Date the allowance was issued/reset.')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'AI model token budget',
                'verbose_name_plural': 'AI model token budgets',
                'db_table': 'ai_ai_model_token_budget',
                'ordering': ('label',),
            },
        ),
    ]
