# Generated by Django 5.1.4 on 2026-06-21 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_aimodeltokenbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('report', models.JSONField(blank=True, default=dict)),
                ('programming_language_id', models.IntegerField(blank=True, null=True)),
                ('programming_language_name', models.CharField(blank=True, default='', max_length=255)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('topic_name', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_id', models.IntegerField(blank=True, null=True)),
                ('prompt_name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI model test run',
                'verbose_name_plural': 'AI model test runs',
                'db_table': 'ai_ai_model_test_run',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AIModelTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(db_index=True, max_length=128)),
                ('model_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=16)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('short_response', models.TextField(blank=True, default='')),
                ('raw_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai.aimodeltestrun')),
            ],
            options={
                'verbose_name': 'AI model test result',
                'verbose_name_plural': 'AI model test results',
                'db_table': 'ai_ai_model_test_result',
                'ordering': ('model_title',),
                'constraints': [models.UniqueConstraint(fields=('run', 'model_key'), name='ai_model_test_result_run_model_uniq')],
            },
        ),
    ]
