# Generated by Django 5.1.4 on 2026-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_aimodeltestrun_aimodeltestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodeltestrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aimodeltestrun',
            name='total_models',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
