# Generated by Django 5.1.4 on 2026-07-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0023_prompt_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='task_node_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
