# Generated by Django 5.1.4 on 2026-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0024_add_task_fields_to_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Содержание обновления')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('commit_hash', models.CharField(blank=True, default='', max_length=40, verbose_name='Хэш коммита')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновления',
                'db_table': 'ai_update_log',
                'ordering': ('-commit_date', '-created_at', '-id'),
            },
        ),
    ]
