# Generated by Django 5.1.4 on 2026-08-06 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0027_favorites_epoch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiappsettings',
            options={'verbose_name': 'Настройки ИИ-приложения', 'verbose_name_plural': 'Настройки ИИ-приложения'},
        ),
        migrations.AlterModelOptions(
            name='aimodelavailability',
            options={'ordering': ('model_title',), 'verbose_name': 'Доступность модели', 'verbose_name_plural': 'Доступность моделей'},
        ),
        migrations.AlterModelOptions(
            name='aimodelhealthrun',
            options={'ordering': ('-window_date',), 'verbose_name': 'Прогон проверки моделей', 'verbose_name_plural': 'Прогоны проверки моделей'},
        ),
        migrations.AlterModelOptions(
            name='aimodeltestresult',
            options={'ordering': ('model_title',), 'verbose_name': 'Результат тестирования модели', 'verbose_name_plural': 'Результаты тестирования модели'},
        ),
        migrations.AlterModelOptions(
            name='aimodeltestrun',
            options={'ordering': ('-started_at',), 'verbose_name': 'Прогон тестирования модели', 'verbose_name_plural': 'Прогоны тестирования модели'},
        ),
        migrations.AlterModelOptions(
            name='airequestlog',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Журнал запросов к ИИ', 'verbose_name_plural': 'Журнал запросов к ИИ'},
        ),
        migrations.AlterModelOptions(
            name='externaldlaccount',
            options={'verbose_name': 'Внешняя учётная запись DL', 'verbose_name_plural': 'Внешние учётные записи DL'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'verbose_name': 'Промпт', 'verbose_name_plural': 'Промпты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='aiappsettings',
            name='favorites_epoch',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата отсечки фаворитов'),
        ),
        migrations.AlterField(
            model_name='aiappsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='aiappsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='checked_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Проверена'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступна'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='last_http_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='last_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='model_key',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Ключ модели'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='model_title',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа, мс'),
        ),
        migrations.AlterField(
            model_name='aimodelavailability',
            name='window_date',
            field=models.DateField(db_index=True, verbose_name='Окно проверки'),
        ),
        migrations.AlterField(
            model_name='aimodelhealthrun',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='aimodelhealthrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='aimodelhealthrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат'),
        ),
        migrations.AlterField(
            model_name='aimodelhealthrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aimodelhealthrun',
            name='window_date',
            field=models.DateField(unique=True, verbose_name='Окно проверки'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Время ответа, с'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='model_key',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Ключ модели'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='model_title',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='prog_lang_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Язык программирования (снимок)'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='raw_response',
            field=models.TextField(blank=True, default='', verbose_name='Полный ответ'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai.aimodeltestrun', verbose_name='Прогон'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='short_response',
            field=models.TextField(blank=True, default='', verbose_name='Краткий ответ'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='ai.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Токенов'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='topic_id_snapshot',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID темы (снимок)'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='topic_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тема (снимок)'),
        ),
        migrations.AlterField(
            model_name='aimodeltestresult',
            name='verdict',
            field=models.CharField(blank=True, choices=[('solved', 'Решено'), ('failed', 'Не решено'), ('skipped', 'Пропущено')], db_index=True, max_length=8, null=True, verbose_name='Вердикт'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='programming_language_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID языка'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='programming_language_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='prompt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID промпта'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='prompt_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='run_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID прогона'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='run_type',
            field=models.CharField(choices=[('single', 'Single (find-error)'), ('batch', 'Batch (solve)')], db_index=True, default='single', max_length=16, verbose_name='Тип прогона'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID темы'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='topic_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='total_models',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего моделей'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Время ответа, с'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='external_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID пользователя dl.gsu.by'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='mode',
            field=models.CharField(blank=True, choices=[('chat', 'Чат'), ('solve', 'Решить задачу'), ('find_error', 'Найти ошибку'), ('arm', 'ARM')], default='', max_length=16, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='model_names',
            field=models.JSONField(blank=True, default=list, verbose_name='Модели'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='programming_language_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID языка'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='programming_language_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='prompt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID промпта'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='prompt_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получен'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='response_text',
            field=models.TextField(blank=True, verbose_name='Ответ модели'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='sent_at',
            field=models.DateTimeField(verbose_name='Отправлен'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='source',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('arm', 'ARM')], default='websocket', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='task_node_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID задачи DL'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Токенов'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID темы'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='external_first_name',
            field=models.CharField(blank=True, default='', help_text='Имя из dl.gsu.by', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='external_last_name',
            field=models.CharField(blank=True, default='', help_text='Фамилия из dl.gsu.by', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='external_login',
            field=models.CharField(help_text='Последний известный логин dl.gsu.by', max_length=255, verbose_name='Логин dl.gsu.by'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='external_user_id',
            field=models.CharField(db_index=True, help_text='ID пользователя из API dl.gsu.by', max_length=255, unique=True, verbose_name='ID пользователя dl.gsu.by'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='externaldlaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_dl_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='language_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name_fr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (FR)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text_fr',
            field=models.TextField(blank=True, default='', verbose_name='Текст (FR)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text_override',
            field=models.TextField(blank=True, null=True, verbose_name='Переопределение текста'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='shared_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_prompts', to='ai.sharedprompt', verbose_name='Общий препромпт'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='prompttestcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='prompttestcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='actual_response',
            field=models.TextField(blank=True, default='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='case_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название кейса (снимок)'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='diff_hint',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подсказка различий'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Время ответа, с'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='expected_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='Эталон (снимок)'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='mode_snapshot',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Режим (снимок)'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='model_key',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Ключ модели'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='model_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='prog_lang_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Язык программирования (снимок)'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai.prompttestrun', verbose_name='Прогон'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='ai.prompttestcase', verbose_name='Тест-кейс'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Токенов'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='topic_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тема (снимок)'),
        ),
        migrations.AlterField(
            model_name='prompttestresult',
            name='verdict',
            field=models.CharField(choices=[('match', 'Совпадает'), ('mismatch', 'Отклонение'), ('skipped', 'Пропущен')], db_index=True, default='mismatch', max_length=16, verbose_name='Вердикт'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='model_key',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Ключ модели'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='model_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='prompt_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID промпта'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='prompt_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='run_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID прогона'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='total_cases',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего кейсов'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='ui_language',
            field=models.CharField(default='Русский', max_length=16, verbose_name='Язык интерфейса'),
        ),
        migrations.AlterField(
            model_name='prompttestrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_shared_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='shared_prompts', to='ai.programminglanguage', verbose_name='Языки программирования'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_name_fr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (FR)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text',
            field=models.TextField(help_text='Доступные плейсхолдеры: {language}/{язык} - язык программирования, {topic}/{тема} - тема.', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text_fr',
            field=models.TextField(blank=True, default='', verbose_name='Текст (FR)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='task',
            name='node_id',
            field=models.PositiveIntegerField(db_index=True, help_text='Идентификатор узла задачи на dl.gsu.by (nodeId).', unique=True, verbose_name='ID узла DL'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Заполняется из get-task-info (поле taskId).', null=True, verbose_name='ID задачи DL'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='programming_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.programminglanguage', verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_fr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (FR)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
