# Generated by Django 5.1.4 on 2026-08-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0030_reclassify_false_error_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodeltestresult',
            name='code',
            field=models.TextField(blank=True, default='', verbose_name='Код программы'),
        ),
        migrations.AddField(
            model_name='aimodeltestresult',
            name='dl_comment',
            field=models.TextField(blank=True, default='', verbose_name='DL: итог тестов'),
        ),
        migrations.AddField(
            model_name='aimodeltestresult',
            name='dl_error',
            field=models.TextField(blank=True, default='', verbose_name='DL: ошибка'),
        ),
        migrations.AddField(
            model_name='aimodeltestresult',
            name='dl_queue_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='DL: queueId'),
        ),
        migrations.AddField(
            model_name='aimodeltestresult',
            name='file_extension_snapshot',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Расширение (снимок)'),
        ),
    ]
