# Generated by Django 5.1.4 on 2026-08-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0032_cmp_to_mpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodeltestrun',
            name='course_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID курса DL'),
        ),
        migrations.AlterField(
            model_name='aimodeltestrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='mode',
            field=models.CharField(blank=True, choices=[('chat', 'Чат'), ('solve', 'Решить задачу'), ('find_error', 'Найти ошибку'), ('arm', 'ARM'), ('batch_solve', 'Пакетное решение')], default='', max_length=16, verbose_name='Режим'),
        ),
    ]
