# Generated by Django 5.1.4 on 2026-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0033_batch_solve_course_id_and_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodeltestrun',
            name='run_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры запуска (форма)'),
        ),
        migrations.AddField(
            model_name='prompttestrun',
            name='run_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры запуска (форма)'),
        ),
    ]
