# Generated by Django 5.1.4 on 2026-09-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0034_aimodeltestrun_run_params_prompttestrun_run_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmPromptBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('solve', 'Пакетное решение'), ('find_error', 'Поиск ошибки')], max_length=16, verbose_name='Вид ARM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arm_prompt_bindings', to='ai.programminglanguage', verbose_name='Язык программирования')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arm_bindings', to='ai.prompt', verbose_name='Препромпт')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arm_prompt_bindings', to='ai.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Привязка препромпта ARM',
                'verbose_name_plural': 'Привязки препромптов ARM',
                'db_table': 'ai_arm_prompt_binding',
                'constraints': [models.UniqueConstraint(fields=('programming_language', 'topic', 'mode'), name='unique_arm_prompt_binding')],
            },
        ),
    ]
