# Generated by Django 5.1.4 on 2026-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0035_armpromptbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Ключ модели')),
                ('model_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название модели')),
                ('solved_count', models.PositiveIntegerField(default=0, verbose_name='Решено задач')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего задач (решено+провалено)')),
                ('duration_count', models.PositiveIntegerField(default=0, verbose_name='Измерений времени')),
                ('duration_sum', models.FloatField(default=0.0, verbose_name='Сумма времени, сек')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика модели',
                'verbose_name_plural': 'Статистика моделей',
                'db_table': 'ai_ai_model_stats',
                'ordering': ('-solved_count',),
            },
        ),
    ]
