# Generated by Django 5.1.4 on 2026-09-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0036_aimodelstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armpromptbinding',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arm_prompt_bindings', to='ai.topic', verbose_name='Тема'),
        ),
        migrations.AddConstraint(
            model_name='armpromptbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', True)), fields=('programming_language', 'mode'), name='unique_arm_prompt_binding_language'),
        ),
    ]
