# Generated by Django 5.1.4 on 2026-09-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0037_alter_armpromptbinding_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiappsettings',
            name='batch_run_names',
            field=models.JSONField(blank=True, default=dict, verbose_name='Названия прогонов (ключ — дата-время ISO)'),
        ),
    ]
