# Generated by Django 5.1.4 on 2026-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0038_aiappsettings_batch_run_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldlaccount',
            name='dl_email',
            field=models.CharField(blank=True, default='', help_text='Email из dl.gsu.by (get-user-info)', max_length=255, verbose_name='Email dl.gsu.by'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_form',
            field=models.CharField(blank=True, default='', help_text='Форма обучения (education.form)', max_length=255, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_form_letter',
            field=models.CharField(blank=True, default='', help_text='Класс/буква (education.formLetter)', max_length=255, verbose_name='Класс (буква)'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_group_mask_id',
            field=models.CharField(blank=True, default='', help_text='Группа (education.groupMaskId)', max_length=255, verbose_name='Группа (groupMaskId)'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_school_id',
            field=models.CharField(blank=True, default='', help_text='ID школы (education.schoolId)', max_length=255, verbose_name='Школа: ID'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_school_kind',
            field=models.CharField(blank=True, default='', help_text='Тип школы (education.schoolKind)', max_length=255, verbose_name='Школа: тип'),
        ),
        migrations.AddField(
            model_name='externaldlaccount',
            name='education_school_no',
            field=models.CharField(blank=True, default='', help_text='Номер школы (education.schoolNo)', max_length=255, verbose_name='Школа: номер'),
        ),
    ]
