# Generated by Django 5.1.4 on 2026-09-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0039_externaldlaccount_dl_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='mode',
            field=models.CharField(blank=True, choices=[('chat', 'Чат'), ('solve', 'Решить задачу'), ('find_error', 'Найти ошибку'), ('arm', 'ARM'), ('batch_solve', 'Пакетное решение'), ('testing', 'Тестирование')], default='', max_length=16, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='source',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('arm', 'ARM'), ('http', 'HTTP')], default='websocket', max_length=32, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_node_id', models.PositiveIntegerField(db_index=True, verbose_name='ID задачи DL')),
                ('programming_language_id', models.IntegerField(blank=True, null=True, verbose_name='ID языка программирования')),
                ('file_extension', models.CharField(blank=True, default='', max_length=16, verbose_name='Расширение файла')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('verdict', models.CharField(choices=[('pending', 'Тестируется'), ('passed', 'Тестирование пройдено'), ('failed', 'Тестирование не пройдено')], default='pending', max_length=16, verbose_name='Вердикт')),
                ('dl_comment', models.TextField(blank=True, default='', verbose_name='Комментарий DL')),
                ('model_key', models.CharField(blank=True, default='', max_length=128, verbose_name='Ключ модели')),
                ('model_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название модели')),
                ('queue_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Queue ID DL')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен на тестирование')),
                ('external_user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID пользователя dl.gsu.by')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Сколько раз выдавался из кэша')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_solutions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('test_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_solutions', to='ai.airequestlog', verbose_name='Запись журнала тестирования')),
            ],
            options={
                'verbose_name': 'Решённая задача (кэш кода)',
                'verbose_name_plural': 'Решённые задачи (кэш кода)',
                'db_table': 'ai_task_solution',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('task_node_id', 'programming_language_id'), name='unique_task_solution_node_lang')],
            },
        ),
    ]
