# Generated by Django 5.1.4 on 2026-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0041_migrate_base_fields_to_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_name',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='sharedprompt',
            name='prompt_name',
        ),
        migrations.RemoveField(
            model_name='sharedprompt',
            name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='prompt_text_ru',
            field=models.TextField(blank=True, default='', help_text='Доступные плейсхолдеры: {language}/{язык} - язык программирования, {topic}/{тема} - тема.', verbose_name='Текст (RU)'),
        ),
    ]
