# Generated by Django 5.1.4 on 2026-09-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0042_remove_prompt_prompt_name_remove_prompt_prompt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolution',
            name='prompt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID препромпта'),
        ),
        migrations.AddField(
            model_name='tasksolution',
            name='prompt_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Препромпт'),
        ),
        migrations.AddField(
            model_name='tasksolution',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID темы'),
        ),
        migrations.AddField(
            model_name='tasksolution',
            name='topic_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тема'),
        ),
    ]
