# Generated by Django 5.1.4 on 2026-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0043_tasksolution_prompt_id_tasksolution_prompt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='mode',
            field=models.CharField(choices=[('solve', 'Реши задачу'), ('find_error', 'В чём ошибка')], db_index=True, default='solve', help_text='В каком режиме страницы предлагается этот промпт.', max_length=16, verbose_name='Режим'),
        ),
    ]
