# Generated by Django 5.1.4 on 2026-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0046_tasksolution_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolution',
            name='tree_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Путь в дереве задач DL'),
        ),
    ]
