# Generated by Django 5.1.4 on 2026-09-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0047_tasksolution_tree_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='programming_language',
            field=models.ForeignKey(blank=True, help_text='Без темы — препромпт действует на весь язык.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='ai.programminglanguage', verbose_name='Язык программирования'),
        ),
    ]
