# Generated by Django 5.1.4 on 2026-09-22 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0048_prompt_programming_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPinnedBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закреплён')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='ai.airequestlog', verbose_name='Запись журнала (прогон)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_batch_runs', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрепил')),
            ],
            options={
                'verbose_name': 'Закреплённый пакетный прогон',
                'verbose_name_plural': 'Закреплённые пакетные прогоны',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'log'), name='ai_pinned_batch_run_user_log_uniq')],
            },
        ),
    ]
