# Generated by Django 5.1.4 on 2026-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0049_pinned_batch_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICourseTreeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(unique=True, verbose_name='Курс DL (courseId)')),
                ('tree', models.JSONField(default=list, verbose_name='Дерево (JSON)')),
                ('task_count', models.PositiveIntegerField(default=0, verbose_name='Задач в дереве')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Кэш дерева курса DL',
                'verbose_name_plural': 'Кэши деревьев курсов DL',
            },
        ),
    ]
