# Generated by Django 5.1.4 on 2026-10-08 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0052_add_update_log_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWizardSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32, verbose_name='Страница (scope тура)')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия текстов подсказок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда пройдено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_seen', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пройденный онбординг',
                'verbose_name_plural': 'Пройденные онбординги',
                'db_table': 'ai_wizard_seen',
                'ordering': ('user_id', 'scope'),
                'constraints': [models.UniqueConstraint(fields=('user', 'scope'), name='ai_wizard_seen_user_scope_uniq')],
            },
        ),
    ]
